### ISSUE TITLE
Issues with installing jhelioviewer on Linux system

### ISSUE THREAD

**Issue by anweshaM** [Helioviewer-Project/JHelioviewer-SWHV#159] opened 2021-02-22 11:57 UTC
I downloaded the software and extracted it from the its tar.gz file.  Then I ran the following command: **java -jar JHelioviewer.jar**

How to proceed further to open the application?

**Here is the error:**
![Screenshot from 2021-02-22 12-55-20](https://user-images.githubusercontent.com/39050383/108705319-700f2f00-750d-11eb-97c2-7a36e70e79ec.png)

**[anwesham@glinka jhv-2.15.7.9411]$** java -jar JHelioviewer.jar
2021-02-22 12:48:00,526 [main] INFO  root - JHelioviewer started with command-line options:
2021-02-22 12:48:00,654 [main] INFO  root - JHV/SWHV-2.15.7.9411 (amd64 Linux 3.10.0-1160.15.2.el7.x86_64) Red Hat, Inc. JRE 1.8.0_282 13.9GB 32CPU
2021-02-22 12:48:01,082 [main] TRACE class org.ehcache.core.Ehcache-JPIPLevel - Initializing
2021-02-22 12:48:01,244 [main] DEBUG class org.ehcache.core.Ehcache-JPIPLevel - Initialize successful.
2021-02-22 12:48:01,272 [main] TRACE class org.ehcache.core.Ehcache-JPIPStream - Initializing
2021-02-22 12:48:01,397 [main] DEBUG class org.ehcache.core.Ehcache-JPIPStream - Initialize successful.
2021-02-22 12:48:02,036 [AWT-EventQueue-0] INFO  root - Start main window
2021-02-22 12:48:03,180 [AWT-EventQueue-0] **ERROR root** - GLInfo > Profile GL4bc is not available on X11GraphicsDevice[type .x11, connection :0, unitID 0, handle 0x7f07ec7a26d0, owner true, ResourceToolkitLock[obj 0x61dbd15a, isOwner true, <5496596c, 45ac2321>[count 1, qsz 0, owner <AWT-EventQueue-0>]]], but: [GLProfile[GLES1/GLES1.hw], GLProfile[GLES2/GLES3.hw], GLProfile[GL2ES1/GLES1.hw], GLProfile[GL4ES3/GL4.hw], GLProfile[GL2ES2/GL4.hw], GLProfile[GL4/GL4.hw], GLProfile[GLES3/GLES3.hw], GLProfile[GL4/GL4.hw], GLProfile[GL3/GL4.hw], GLProfile[GL2GL3/GL4.hw]]
2021-02-22 12:49:11,796 [Thread-2] TRACE class org.ehcache.core.Ehcache-JPIPLevel - Closing
X11Util.Display: Shutdown (JVM shutdown: true, open (no close attempt): 1/1, reusable (open, marked uncloseable): 0, pending (open in creation order): 1)
X11Util: Open X11 Display Connections: 1
X11Util: Open[0]: NamedX11Display[:0, 0x7f07ec7a26d0, refCount 1, unCloseable false]
2021-02-22 12:49:11,829 [Thread-2] DEBUG class org.ehcache.core.Ehcache-JPIPLevel - Close successful.
2021-02-22 12:49:11,838 [Thread-2] TRACE class org.ehcache.core.Ehcache-JPIPStream - Closing
2021-02-22 12:49:11,867 [Thread-2] DEBUG class org.ehcache.core.Ehcache-JPIPStream - Close successful.

**Comment by bogdanni** [comment] 2021-02-22 12:04
The issue is that it cannot detect the right OpenGL profile for your system.
Could you please try with the RPM from http://swhv.oma.be/download_test/ ?
Install it with `rpm -i JHelioviewer_4_0_0_amd64.rpm` with root privileges.

**Comment by anweshaM** [comment] 2021-02-22 12:47
This is what I get using rpm*. *I do not have sudo privilege on this
system, if that is necessary.

*[anwesham@glinka Downloads]$ *rpm -i JHelioviewer_4_0_0_amd64.rpm
error: Failed dependencies:
JHelioviewer is obsoleted by (installed)
esat-jhelioviewer-1:2.15.7.9411-1.el7.esat.x86_64

**Comment by bogdanni** [comment] 2021-03-31 21:41
This was fixed in communication with the user.

**Comment by bogdanni** [comment] 2021-03-31 21:46
In addition, the software will also be released in form of archive for the users who have insufficient privileges to install software packages.

The command to run JHV (as of now) is
`java -cp JHelioviewer.jar:natives-linux.jar:natives-macos.jar:natives-windows.jar org.helioviewer.jhv.JHelioviewer` as explained in the Manual installation section of the user manual.

**Closed by bogdanni** 2021-03-31 21:46 UTC
