### ISSUE TITLE
GSFC data sources, all 10 second cadence AIA/HMI data, are offline and gone.

### ISSUE THREAD

**Issue by superkuh** [Helioviewer-Project/JHelioviewer-SWHV#97] opened 2018-09-25 16:43 UTC
Starting sometime early in the morning (ie, midnight) September 24/25th the Goddard Space Flight Center data sources went offline. I thought it might be due to me using an old version of JHelioviewer (jhv-2.11.3.8731) so I updated to the latest (jhv-2.15.2.9166) but that doesn't work either.

All GSFC resources return "Error getting the data: 0". The alternative data sources like ROB and IAS (which work fine) only have 10 minute cadence AIA and HMI data and are pretty useless for most tasks.

So far I cannot tell if I have been IP banned or GSFC is simply offline. But it's been half a day.

2018-09-25 16:41:13,085 [JHVWorker-MAIN--LoadRemote] DEBUG root - Response: {"errno":1,"error":"0"}
2018-09-25 16:41:13,085 [JHVWorker-MAIN--LoadRemote] ERROR root - Data query returned error: 0
2018-09-25 16:42:46,804 [JHVWorker-MAIN--LoadRemote] DEBUG root - Response: {"errno":1,"error":"0"}
2018-09-25 16:42:46,805 [JHVWorker-MAIN--LoadRemote] ERROR root - Data query returned error: 0
2018-09-25 16:46:02,672 [JHVWorker-MAIN--LoadRemote] DEBUG root - Response: {"errno":1,"error":"0"}
2018-09-25 16:46:02,672 [JHVWorker-MAIN--LoadRemote] ERROR root - Data query returned error: 0

**Comment by bogdanni** [comment] 2018-09-25 17:59
Thanks for the report. Yes, I believe the GSFC server returns bad data right now:
`curl -g 'https://api.helioviewer.org/v2/getDataSources/?verbose=true&enable=[TRACE,Hinode,Yohkoh,STEREO_A,STEREO_B,PROBA2]'`
results in 
`{"errno":1,"error":"0"}`

It's the people at GSFC who need to be contacted: https://github.com/Helioviewer-Project/helioviewer.org

Anyway, one of them monitors the issues here as well, so maybe he will soon see your report. Those sort of troubles are usually transitory.

I think the IAS server should have a full mirror of GSFC data, so they are, in theory, interchangeable. The ROB server has, indeed, only a couple of AIA wavelengths, at a low sampling frequency.

**Comment by wafels** [comment] 2018-09-25 18:34
Hi,

We think the issue is being caused by someone (or more than one person)
making many thousands of requests in a short period of time.  This
increased traffic is causing significant problems in furnishing other
services to other users.  We are attempting to fix this issue.
Jack

**Comment by superkuh** [comment] 2018-09-25 18:50
Sorry! The problem started when I was attempting to generate a movie in JHelioviewer. It crashed and became non-responsive. It took me a while to kill it. During that time it may have been in a bad loop and sent those many request. But that was with the old JHelioviewer. Hopefully the new one will not repeat it.

**Comment by wafels** [comment] 2018-09-25 18:58
We are still experiencing this issue so I don't think it was your
non-responsive copy of JHelioviewer. We also had this problem before Sep
24/25.

**Comment by bogdanni** [comment] 2019-11-13 10:29
Closing this as it seems a transient server issue.

**Closed by bogdanni** 2019-11-13 10:29 UTC
