### ISSUE TITLE
4.4.0 failing to install on Windows 10

### ISSUE THREAD

**Issue by davidsaroff** [Helioviewer-Project/JHelioviewer-SWHV#224] opened 2023-01-15 02:19 UTC
The JHelioviewer 4.4.0 windows installer fails with the message "Files\JHelioviewer\.install4j\i4j_extf_1_1gymj79_6dc3o4.png Could not created this file." 

I'm running the installer as Administrator, and have Norton 360 off.

How to proceed?

**Comment by bogdanni** [comment] 2023-01-15 08:59
There must something else interfering with the installation process. A clean Windows 10 installation does not exhibit this error.

**Comment by davidsaroff** [comment] 2023-01-16 23:13
There were several .png images left over from previous installations. When
the installer tried to write the new files, there was an error, since files
with those names already existed. Deleting them solved the problem. A
complete uninstall would have as well I presume.

**Comment by bogdanni** [comment] 2023-06-19 18:01
I regularly re-install on Windows and don't see this problem. I tried canceling the installation process at several stages and could not reproduce. Either there was an external interference from something like an antivirus program, or there is/was a bug in the generated installation program.

Closing this, please reopen if it happens again and there is a way to reproduce it.

**Closed by bogdanni** 2023-06-19 18:01 UTC
