### ISSUE TITLE
JHV command line documentation

### ISSUE THREAD

**Issue by MedocGFI** [Helioviewer-Project/JHelioviewer-SWHV#78] opened 2018-06-11 10:31 UTC
Hello,

We need to use JHV in command line. 
The current documentation using the jar with -jhv <options> seems to be obsolet.
Can we have the documentation for the new use of it ?

Cdt,
MedocGFI.

**Comment by ebuchlin** [comment] 2018-06-11 13:36
This is a duplicate of #73 .

**Closed** 2019-12-01 08:30 UTC
